import os

print("=" * 40)
print("🎉 찾았습니다! secret.py 실행 성공!")
print("=" * 40)
print()
print(f"현재 위치: {os.getcwd()}")
print()
print("여기까지 온 경로:")
print("  cd drill01_navigation")
print("  cd chapter1")
print("  cd deeper")
print("  python secret.py")
print()
print("루트로 돌아가려면: cd ../../..")
